inherit_gem:
  bixby: bixby_default.yml
AllCops:
  DisplayCopNames: true
  TargetRubyVersion: 2.4
  Exclude:
    - 'bin/*'
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - '*.gemspec'
Style/StringLiterals:
  EnforcedStyle: double_quotes
